  <header id="background-container">
    <!--Logo de Gijon -->
    <div class="portadaLogo">
      <div class="logos">
        <div> <img class="logo" src="images/Logo Gijon.png" alt="Ayto Gijón" title="Ayto Gijón" /> </div>
        <div> <img class="logo" src="images/logoet.png" alt="Escuela Taller" title="Escuela Taller" /></div>
      </div>

      <div class="portadaMenu">
        <button id="botonHamburguesa">
          <span>&#9776;</span>
        </button>

        <nav id="menu">
          <ul id="menunav">
            <li><a href="agenda/index.html">Agenda</a></li>
            <li><a id="botonModus" href="modulo/index.html">M&oacute;dulo</a></li>
            <li><a href="equipo/index.html">Equipo</a></li>
            <li><a href="alumnado/index.html">Alumnado</a></li>
            <li><a href="instalaciones/index.html">Instalaciones</a></li>
            <li><a href="mapaweb/index.html">Mapa de la Web</a></li>
            <li><a href="manual/manualdeusuario.pdf" target="_blank">Manual de usuario</a></li>
          </ul>
        </nav>
      </div>
    </div>

    <!--Texto de acompañamiento-->
    <div class="portadaTexto">
      <h1>Escuela Taller "Gijón Acompa&nacute;a" 2023</h1>
      <p class="textoIntro">Las Escuelas Taller son programas mixtos de empleo y formación de carácter temporal,
        que
        tienen por objeto mejorar la empleabilidad de las personas desempleadas mediante la cualificación en
        certificados de profesionalidad y la ejecución de obras o servicios de utilidad pública, que sirvan de
        experiencia práctica en el ámbito de la formación profesional recibida. La finalidad es facilitar la
        inserción
        laboral de las personas participantes.</p>
      <p class="textoIntro">Las Escuelas Taller van dirigidas a jóvenes en situación de desempleo de edades
        comprendidas
        entre los 16 y los 30 años. Tienen una duración máxima de 18 meses, de los cuales 3 meses pertenecen
        exclusivamente a formación y 15 meses con contrato de trabajo de formación.</p>
    </div>

    <div class="botonPortada">
      <button class="bajar"><a href="#anclaUN"><img src="images/flecha.png" alt="paco"></a></button>
    </div>
  </header>