  <footer>
    <section class="f1">
      <img src="images/acces.png" alt="accesibilidad " /><!-- imagen access AAA HTML5 -->
      <p class="dire">Accesibilidad: </p>
      <p class="dire">AAA HTML5</p>
    </section>

    <section class="f2">
      <p><a href="legal/" class="links">Aviso legal</a></p>
      <p><a href="proteccion_datos/index.html" class="links">Proteccion de datos</a></p>
      <p><a href="ubicacion/index.html" class="links">Ubicaci&oacute;n</a> </p>
    </section>

    <section class="f3">
      <p class="links">Contacto:</p>
      <p class="dire">630 76 16 62</p>
      <p class="dire">985 18 16 13</p>
      <p class="dire">985 86 57 05</p>
    </section>

  </footer>
